### ISSUE TITLE
Need a hook for when the lexer is finished lexing a buffer

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#1]
I have hacked one of these into the core for now.  I did it in a not-particularly-good way, which was to call the hook immediately after the lexing is finished, which means it will dispatch from multiple threads at the same time if the lexer runs in parallel.  I then serialized the results in my hook handler by placing the resulting buffer ids into a queue which my render hook dequeues later to ensure it only happens on a single thread.

My suggestion here would be to have 4coder add an official hook for "lexing complete", but it should do the serialization beforehand, and only call the hook from one thread.  It could pass all buffers which have finished lexing since the last time the hook was called in case the custom layer can accelerate processing of multiple buffers at once.

\- Casey

**Comment by 4coder-editor** [comment]
I addressed this with an "edit finished" hook.  The core guarantees to call the hook and pass in all buffers that have been edited since the last call of the hook.  Buffers with tokens are not eligible to be marked as "edit finished" until their tokens are updated internally.  This means if the tokens never complete because more text is inserted and the lexing has to restart, the buffer is never marked as "edit finished".

The hook is rated limited so that several edits can be accumulated between consecutive calls.  All buffers with finished edits are passed by an array to the hook.

**Comment by cmuratori** [comment]
That sounds awesome!

\- Casey
