### ISSUE TITLE
Better window split control

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#12]
Two things here:

1) There should be a way to specify the type of window subdivision you want.  Percentage is one way, and good, but you also want "fixed number of lines" so you can do things like create windows that hold query bars or other things like this that need a specific number of lines to work properly.

2) It is currently very confusing to work with window layouts because the API doesn't really make it clear how split percentages are interpreted, or how the hierarchy of panels is laid out.  From the API perspective, it just looks like "windows that have split percentages", but there's not much information about how they are related, or how you might create a specific window tiling, and I often got results that surprised me when I tried to make certain things I thought would be simple.

\- Casey

**Comment by 4coder-editor** [comment]
1. Added support for a fixed number of pixels.  I didn't go with lines because, although each "leaf" panel has a specific font and therefore a specific line height, a split ("internal" panel) could have different fonts on its two sides, or could even have more internal panels, so it seemed more confusing than it should be.  There may be some way to make this make sense, for instance setting a split to lookup it's font from a particular leaf when setting the split.  The obvious concern is that if you want to guarantee exactly eight lines of height no matter what, having to change the height whenever the font changes (which can happen indirectly by changing the buffer) will be quite difficult.  It's going to take a little time of me playing with it to figure it out.

**Comment by cmuratori** [comment]
Fixed pixels is probably fine until things get clarified at a higher level (eg., #2).  It will definitely work for my use-case.

\- Casey
