### ISSUE TITLE
Copy from other application 

### ISSUE THREAD

**Issue by embededhell** [4coder-editor/4coder#154]
I’m not sure if this is on the issue list, I’m sure I’ve seen it talked about.
The dreaded copy from another applications bug is back!
I remember this being fixed in the early days, but it seems to be back with the same symptoms.
Copy from a different application, even another 4coder instance and 4coder misses the clipboard event. Hammering copy several times normally makes it wake up.

**Comment by 4coder-editor** [comment]
It turns out that WM_CLIPBOARDUPDATE doesn't have perfect reliability. I've address this by 1. Switching away from always trying to collect all clipboard events, and instead specifically querying the clipboard at the moment the user pastes, thus making it pretty hard to miss a copy. 2. When 4coder is put into clip collection mode it periodically sends itself wake ups to make it more likely to catch all clips. The change is in 4.1.4.

**Comment by bumboni** [comment]
This bug still happens, for me.
