### ISSUE TITLE
line numbers don't appear with toggle_line_numbers, get pink region instead

### ISSUE THREAD

**Issue by GreyDodger** [4coder-editor/4coder#155]
![image](https://user-images.githubusercontent.com/2457708/72667430-92b54700-39e1-11ea-872d-6e3165d0145d.png)

**Comment by aolo2** [comment]
IIRC this is what happens when the color theme doesn't specify colors for line number margin (foreground and background). To test this you can switch to the default theme.

There was also a problem where theme files were not being loaded (see [issue 101](https://github.com/4coder-editor/4coder/issues/101)), but that was fixed in 4.1.1.

**Comment by 4coder-editor** [comment]
This was a problem with the theme files which did not include their line number background and text color. Fixed in 4.1.3.
