### ISSUE TITLE
Things that look like String in the API should just use String

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#17]
Right now it is hard to work with String because most things in the API don't actually use it, so you're constantly using macros or just manually reassembling things.  Let's just require the use of String everywhere, and be done with it!  People who need to assemble strings can still use make_string() as necessary, but when staying entirely within 4coder's paradigm, you should never have to shuffle things back and forth like you do now.

\- Casey

**Comment by 4coder-editor** [comment]
I addressed this by switching over the entire API and then setting up a "transition API" file that reimplements the interface on the new API so that everyone can transition to the new interface when they are by just removing the entire file/parts of the file to track down everything that needs to change.

Everything that takes a char *str, int32_t len now just takes a String.  Everything that fills a char *out, int32_t cap, now takes a String * and _appends_ it's output to the output string if possible, making it pretty convenient to concat the result of an API returned string into other strings.  Whenever returning a string, there is a dedicated parameter that _always_ returns the required output size no matter how much was actually written, and the actual amount written is reflected in the size member of the String.

**Comment by cmuratori** [comment]
That is awesome, I will switch everything i have over to that ASAP.

\- Casey
