### ISSUE TITLE
MinorBug: The first use of Ctrl(+Shift)+T gives a search result with text/code wrapping while its disabled.

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#180]
Version: 4.1.3

**Repro Steps"" 
- Set *enable_code_wrapping = false;* in config.4coder .
- (Re)Start 4Coder, 
- set cursor over a keyword, press Ctrl+shift+T to trigger a search(result), see that it is wrapped. 
- close the search result, 
- trigger another search query. 

**Description of the Result**
see that it is now no longer wrapped. (This seems to go for all subsequent queries, until you/I restart 4Coder)

**Additional notes**
Just a minor bug I noticed.

**System**
OS: Windows X
Graphics Driver (for graphics bugs): NVIDIA 441.41

**Comment by 4coder-editor** [comment]
Search results shouldn't actually be controlled by that flag to begin with. When I follow these steps on the latest version the results are still wrapped with every search, although a lot may have changed. Rather than trying to repro this probably stale bug, I settled for adding a "wrap_output_buffers" option and make sure it's roughly behaving correct. Fix in 4.1.5
