### ISSUE TITLE
Undo doesn't (always?) move the edit-cursor back to the position before the edit.

### ISSUE THREAD

**Issue by jim0** [4coder-editor/4coder#189]
Version: 4.1.3

**Repro Steps (Including a snippet of any potentially related customization code)**
Note where your input-cursor starts
Write code that gets affected by auto-indentation
Undo that code
Note where your input-cursor ends up.

**Description of the Result**
In my experience the cursor ends up where the auto-indentation system would place it, not where the user placed the cursor.

**Additional notes**
I noticed this most when I was undoing an effect of auto indentation. 
I was writing a long list of `if else` like this: 
```
if(if_this){ /*then this*/ } else
if(or_this){ /*then this*/ } else
if(or_this_2){ /*then this*/ } else
{ /*log error */ }
```
and I was undoing the indentation of every `if` after the first since I want the cases to align. 
(I assume you want to keep everything after the `else` as if it was already inside a new scope.)

**System**
OS: Windows10

**Comment by 4coder-editor** [comment]
So this is a little tricky because it's now *always* possible to figure out a cursor for an edit, but I did add in a heuristic for deducing it in the common case where a user is just typing stuff in and stuff like that. Basically as long as you're not posting edits to an off screen buffer, or a buffer in a different view, it now saves a pos_before_edit field, and if it can't do that, it puts in the start of the edit range for that field. Fix in 4.1.5.
