### ISSUE TITLE
Spotty Handling of Key Modifiers

### ISSUE THREAD

**Issue by ryanfleury** [4coder-editor/4coder#195]
Version: 4.1.4

**Repro Steps**
Open up a file like this:
`
// Blank line below this comment.

code

// Blank line above this comment.
`

Hold down left Ctrl. Skip the cursor over the `code` line by moving the cursor up and down. Alternate pressing the arrow keys with `s`, without letting go of left Ctrl.

**Description of the Result**
Notice that `s` characters begin to be input into the buffer, despite continuing to hold Ctrl. These should be registered as Ctrl+s instead of just s.

**System**
OS: Windows 10 Pro, 17763.805

**Comment by 4coder-editor** [comment]
This effect is created by strict matching of key-combos and text input generating whenever a key stroke is not handled. For example, when the down arrow key is held a moment too long, the key combo [ S Control Down ] is registered and since there is no strict match to that combo, it is ignored, and the key press [ S ] goes unhandled, thus letting the keystroke go on to generate a text input event.

The fix for this was to enable both strict matching which runs first, and loose matching after, so that the expected activation of [ S Control ] would happen from the input [ S Control Down ]. Fix in 4.1.5 (and available to anyone with access to the custom layer).
