### ISSUE TITLE
Undoing should move the cursor back to it's original position

### ISSUE THREAD

**Issue by xdnicoco** [4coder-editor/4coder#197]
Currently, undoing moves the cursor to an arbitrary position (I guess it actually doesn't move it at all, it just seems like it's moving because the buffer has changed).
I think a much better behavior would be to save the cursor position and place it where it was before the operation that was undone, because most of the time you'd like to continue editing from that place.

**Comment by 4coder-editor** [comment]
So this is a little tricky because it's now always possible to figure out a cursor for an edit, but I did add in a heuristic for deducing it in the common case where a user is just typing stuff in and stuff like that. Basically as long as you're not posting edits to an off screen buffer, or a buffer in a different view, it now saves a pos_before_edit field, and if it can't do that, it puts in the start of the edit range for that field. Fix in 4.1.5.
