### ISSUE TITLE
Typing Unicode Character Bug

### ISSUE THREAD

**Issue by vominh2012** [4coder-editor/4coder#198]
Version: 4.1.4

**Repro Steps**
Bug happen when i'm typing vietnamse unicode character by using combine of two key.

For example:  if i type 'as' it's show 'á' but when I'm typing fast in 4coder it's show 'aá'

As I notice when typing fast I press 'a' and 's' key down at the same time and then release this bug happen if i pressed key 'a' and 's' separately then it's working fine.

**Description of the Result**
Typing with unicode for a while with using of backspace for delete character crash 4coder

**Additional notes**
Software for typing i'm using at: https://sourceforge.net/projects/unikey/files/unikey-win/4.3%20RC4/unikey43RC4-180714-win64.zip/download

This software working fine on all editor that i'm using even notepad, web browser

**System**
OS: Windows 10

**Comment by 4coder-editor** [comment]
I suspect this relates to an issue with key-bind matching that generally relates to accidentally holding down one key when pressing another. I'll try to test it, but I'm not going to close this issue until I hear back from you here that it is fixed in a future version. Hopefully it'll be fixed in 4.1.5.

**Comment by vominh2012** [comment]
this bug is fixed with version 4.1.5 & 4.1.6, great work! i think we can close this
