### ISSUE TITLE
A few suggestions for the API

### ISSUE THREAD

**Issue by xdnicoco** [4coder-editor/4coder#219]
I have a few suggestions of possible improvements to the API:
-  a function that completes a standalone string from a given buffer (I did a version of that in 4.0 mainly for custom queries, but it seems you have to have the range in the buffer and you can't just specify a needle anymore)
- I wanted to point that in `4coder_data_types.cpp` and also in `4coder_stringf.cpp` there is some inconsistency with how functions regarding pushing strings on an arena are named (`string_u8_push` vs `push_u8_stringf` vs `push_string_copy` etc.) which can be a little frustrating sometimes.
- Shortcuts to create string consts from strings:
```c++
function String_Const_char
SCchar(String_char str){
    String_Const_char string = SCchar(str.str, str.size);
    return(string);
}
function String_Const_u8
SCu8(String_u8 str){
    String_Const_u8 string = SCu8(str.str, str.size);
    return(string);
}
function String_Const_u16
SCu16(String_u16 str){
    String_Const_u16 string = SCu16(str.str, str.size);
    return(string);
}
function String_Const_u32
SCu32(String_u32 str){
    String_Const_u32 string = SCu32(str.str, str.size);
    return(string);
}
```

**Comment by 4coder-editor** [comment]
I don't understand the first bullet point. "Completes a standalone string from a given buffer"?

There are a few things in the string API I wish I hadn't shipped, and I stopped using them, but they are used in a lot of other people's code. So when I standardized to always putting `push_` first, I didn't catch all the places from parts of the library I wasn't using anymore. I have added some macros with the names rearrange with `push_` first so that code doesn't have to transition, but the consistent names should be available now.

Last one is done.

**Comment by xdnicoco** [comment]
The first bullet means a way to complete a given string without necessarily having a corresponding range for in the buffer. Currently `word_complete_iter_init` works with a range from the buffer, so it's not possible to directly complete a standalone string (let's say in a query bar) without searching for the first occurrence of it first and only then initializing with the range.

**Comment by 4coder-editor** [comment]
I've added an init function for it that takes a firsT_buffer to scan and a needle, and another that takes just a needle. It will still search all buffers this way, but in case you only wanted to run word completions for a single buffer you can now call `word_complete_iter_stop_on_this_buffer(it)` after the init to only scan the first buffer (or any time to stop scanning at the end of the current buffer).
