### ISSUE TITLE
show_line_number_margins does not correctly show line numbers

### ISSUE THREAD

**Issue by 5n8ke** [4coder-editor/4coder#226]
Version: beta 4.1.4

**How to reproduce**
With a fresh download of 4coder and the config.4coder option _show_line_number_margins=true_ enabled the editor is expected to show line numbers.

**Result**
The editor shows the margins but not with correct line numbers and the margin is to narrow to display the complete line number.

![4coder line number margins cropped](https://user-images.githubusercontent.com/6875541/80684586-2b219400-8ac6-11ea-8807-31d23c491729.png)

**System**
OS: Windows 10 Education
Graphics Driver (for graphics bugs): Intel HD Graphics 630

**Comment by 4coder-editor** [comment]
I am not able to make anything like this happen.

It looks like it's just putting in totally garbage line numbers and that the margin width would actually be correct if the numbers weren't garbage. Focusing on the garbage problem I'm really pretty stumped about why that would happen, it doesn't make any sense.

The only thing I can think of is maybe the string formatting is doing something really incorrect. I just updated this code for other reasons, and it doesn't have a format string in it anymore.  Maybe it will be fixed in 4.1.5. I'll leave this open until I hear back though.

**Comment by 5n8ke** [comment]
I tried again with beta 4.1.5 and the issue no longer exists.

Thank you for your investigation and quick reply.
