### ISSUE TITLE
list_all_functions_current_buffer is not parsing the first function correctly

### ISSUE THREAD

**Issue by manicombinostics** [4coder-editor/4coder#232]
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**

Create a C file with following contents (notice the empty first lines). The empty lines can also contain a comment.
```


// Comment

void test_function()
{
}

void another_function()
{
}
```

Execute list_all_functions_current_buffer or list_all_functions_current_buffer_lister.

**Description of the Result**

list_all_functions_current_buffer will list the following:
```
repro.cpp:2: 


void test_function()
repro.cpp:6: void another_function()
```

This also affects list_all_functions_current_buffer_lister where the first function would be just empty, but you can jump to that function.

If you place something on the first lines (include, struct, ...) or the function or comment is on line 1, the lister will work correctly.

**Additional notes**

**System**
OS: Windows 10

**Comment by 4coder-editor** [comment]
This happened because the printing function was printing out whitespace tokens including newline characters, and the first function can't find a token before it that clearly marks the beginning of a signature, so it starts from the beginning. Fixed by simply not printing whitespace tokens. Fix in 4.1.6.
