### ISSUE TITLE
Scrolling selects text in notepad-like

### ISSUE THREAD

**Issue by jmrico01** [4coder-editor/4coder#233]
Version: 4.1.5 ( first 4.1.5 issue? 🙃 )

**Repro Steps (Including a snippet of any potentially related customization code)**
1. Set mode to notepad-like
2. Scroll through a file using the mouse scroll wheel
3. If the cursor goes off screen, 4coder will select the text from the cursor's off-screen position to some position of the cursor that's clamped to the screen.

**Description of the Result**

**Additional notes**

**System**
OS: Windows
Graphics Driver (for graphics bugs): N/A I think

**Comment by 4coder-editor** [comment]
Ahh. Trying to make scrolling work while clicking-and-dragging to select also means that scrolling when not clicking-and-dragging causes selection. Fixed this by adding a hard check that the mouse l button is down when scrolling. This means that the l-button HAS to be bound to selection, rebinding to a different selection method won't work with scrolling, but I am guessing that is totally fine. Fixed in 4.1.6.

This fix is 100% in the custom layer, so for users with the ability to modify the custom layer and rebuild the fix is:
**File:** `4coder_base_commands.cpp`
**Command:** `mouse_wheel_scroll`
On the line with `no_mark_snap_to_cursor(app, view);` it should say:
`if (mouse.l){
    no_mark_snap_to_cursor(app, view);
}`
