### ISSUE TITLE
Why do things take Buffer_Summary when they could take Buffer_ID?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#29]
There are a number of commands which do not actually need a Buffer_Summary but which require one.  Buffer_Replace_Range is the most important one.  Because it requires a pointer to a Buffer_Summary even though it only needs the Buffer_ID, it forces the user to maintain a giant structure filled with stuff when a simple integer would have sufficed, not to mention making it confusing as to how much of that structure is still valid information vs. old information.

I would suggest that 99% of the time, IDs should be used (view and buffer), and the only time you would ever pass a _Summary struct would be when you want to fill it out.  If users want convenience functions for this, they can be added to the custom layer, but the API can work with IDs exclusively.

\- Casey

**Comment by 4coder-editor** [comment]
I addressed this by switching over the entire API and then setting up a "transition API" file that reimplements the interface on the new API so that everyone can transition to the new interface when they are by just removing the entire file/parts of the file to track down everything that needs to change.

Everything works on ids now except the 'get' call that returns the summary from the ID.

**Comment by cmuratori** [comment]
This sounds awesome!

\- Casey

**Comment by 4coder-editor** [comment]
Hmm... I've discovered a little issue with this that I'm not exactly sure what to do with yet.  In particular if everything takes IDs then the system that was in place for read only buffers doesn't work anymore.

The way it used to work was:
1. You have the id of the view or buffer you want to use.
2. You request the View_Summary or Buffer_Summary and you say what sort of operation you want to do with it (AccessOpen -> read/write/navigate, AccessProtected -> read/navigate, AccessAll -> read).  You ony get a summary if the view or buffer you requested meets the requirements, otherwise you get a null summary even if the view or buffer did exist.
3. You use the summary in the rest of the operations and since the API ignores operations on invalid summaries, if you requested more permission than you could get, nothing happens.

The problem is that now the API lets you skip step 2, once you have the id you can go straight into doing whatever operations you wanted.  Basically it used to be a type error to not explicitly declare your "intentions" with the view or buffer.

I could easily fix this by having everything in the API that used to take a "summary" take some kind of "handle":
`struct Buffer_Handle{  Buffer_ID buffer_id;  };`

Then I can reintroduce the type enforcement of step 2 with an API that's like: 
`Buffer_Handle
get_buffer_handle_for_access_type(Application_Links *app, Buffer_ID buffer_id, AccessFlags flags);`

And anytime you want to explicity bypass this there can just be helper:
`Buffer_Handle buffer_handle_skip_access(Buffer_ID buffer_id);`

Does this make sense?  Before I go ahead with it I wanted to see if there were any better ideas for how to accomplish this.

**Comment by cmuratori** [comment]
Just so I'm clear, the goal here is to make sure that groups of buffer operations are atomic, so that things which would mutate the buffer and be prevented won't be accompanied by things which, say, move the cursor around, without also having those non-mutating things be prevented too?

\- Casey

**Comment by 4coder-editor** [comment]
This accomplishes a couple of things:

As you described, if I just did a `if (buffer_may_be_edited)` check in replace_range, then yes you could still move the cursor even though the edit never happened.

However, the way it is currently setup, there's a bit more to it.  It might be useful to differentiate the "user" who is literally using 4coder and the "user" who is writing the usage code in the custom layer.  Perhaps "user" and "customizer"?

What a "read only" actually means is read only to the user, the customizer is actually still free to do whatever they want with a read only buffer.  For instance the *messages* buffer is read only, the customizer can edit it, but if the user tries to do any edit operations on it they should fail.  Now imagine being the customizer writing an edit command.  If 2 is not enforced by types what I should write its:
`
CUSTOM_COMMAND(foo){
    View_ID view_id = get_active_view(app);
    View_Summary view_summary = get_view_summary(app, view_id);
    // I now have my buffer id: view_summary.buffer_id
    // but if I don't want this command to mess up *compilation*, *messages*, etc, I better do:
    Buffer_Summary buffer_summary = get_buffer_summary(app, view_summary.buffer_id);
    if (check_access(buffer_summary.access_flags, AccessOpen)){
        // ... the rest of my operation ...
    }
}
`

If 2 is enforced in the way I am proposing now:
`
CUSTOM_COMMAND(foo){
    View_ID view_id = get_active_view(app);
    View_Handle view_handle = get_view_handle_access_type(app, view_id, AccessOpen);
    View_Summary view_summary = get_view_summary(app, view_handle);
    // I now have my buffer id: view_summary.buffer_id
    // but I need a handle
    Buffer_Handle buffer_handle = get_buffer_handle_access_type(app, view_summary.buffer_id, AccessOpen);
    // ... the rest of my operation ...
}
`

Unfortunately, typing it out, these both look a lot more verbose than the old system which was just:
`
CUSTOM_COMMAND(foo){
    View_Summary view = get_active_view(app, AccessOpen);
    // I now have my buffer id: view_summary.buffer_id
    // but I need a summary
    Buffer_Summary buffer = get_buffer(app, view.buffer_id, AccessOpen);
    // ... the rest of my operation ...
}

`

The reason I didn't like this system (which I assume was the same reasoning you had?) was that summaries were really big things to use as handles.

Hmm... I probably need to fiddle with this some more.

**Comment by 4coder-editor** [comment]
Okay I think I understand how to make it work now.  I have to just treat the ids themselves as the choke point, be more selective about returning ids by having all the APIs that return ids take the access flags.  Then it basically becomes:

```
CUSTOM_COMMAND(foo){
    View_ID view_id = get_active_view(app, AccessOpen);
    Buffer_ID buffer_id = get_buffer_from_view(app, view_id, AccessOpen);
    // ... the rest of my operation ...
}
```

The only trick to this is that the summaries can't have ids in them anymore, as that creates a bypass.

**Comment by cmuratori** [comment]
I feel like that is probably good?  One thing that I wasn't sure about with the old API is how much you really want to be passing around Buffer_Summary / View_Summary anyway, because most of the things in there are only valid for like one call.  So it seems like the chances that somebody accidentally uses stale data is high, and in order to try to prevent that, you end up having lots of Buffer_Summary refreshes happening automatically inside API code, but that's only a partial solution (eg., if anyone copied the summary, you're in trouble).

So it seems like maybe the summary thing is a little wonky anyway?  Like is it better to just have a few calls that get the various parts of it, and have people call those?

\- Casey
