### ISSUE TITLE
Better keyboard coverage?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#38]
I don't know if it's worth it or not, but right now 4coder can't actually map some of the keys on the keyboard, such as pause, scroll lock, and print screen.  I'm not sure if it's worth going down the road of 100% coverage, because it may be difficult in the face of international keyboards.  But I don't know.  I believe it would require initializing Raw Input on Windows, since although you get KEYUP's for all these keys normally, you don't get KEYDOWN's for a lot of them because Windows intercepts them when you don't have Raw Input...

\- Casey

**Comment by 4coder-editor** [comment]
Print Screen appears to be the only one for which I can't the KEYDOWN message.  So I've added scroll lock, pause, num lock, and caps lock.

On windows the only keys I cannot get now are Print Screen, the windows key, and the weird context menu key thingy?  I don't want to go down the road of Raw Input because I don't know how that will interfere with my plan for better international support.  For now I think keyboard coverage is maximized on windows.

**Comment by cmuratori** [comment]
I would suspect you could get the "weird context menu key thingy" the same way you get all the other keys, it's not special?  Just add VK_APPS to your mapping table.

\- Casey
