### ISSUE TITLE
Are custom layers built in debug mode?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#42]
By cursory inspection, it seems like perhaps custom layers are built in debug mode, which means almost all the helper code will be in debug mode as well.  This could be causing significant speed issues?  Maybe I am missing somewhere that they are actually built optimized?

\- Casey

**Comment by 4coder-editor** [comment]
Now when calling buildsuper if the second parameter is "release" it will build in release mode.  This forces you to pass a first parameter, but that's usually happening anyway when you're building your own customization so that seems fine to me.

To be clear the invocation for release mode is:
`buildsuper "my_customization_file.cpp" release`

**Comment by cmuratori** [comment]
I am assuming that to build in debug mode as before, the idea is that you just don't pass anything?  Or is the intent we should pass "debug" or something?

\- Casey
