### ISSUE TITLE
Hook that provides a list of buffer ids and edit ranges

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#61]
This would be something that gets called before each render that is a list of every buffer id that has been edited and the list of edit ranges that occurred, so that the index/lister stuff can adjust all the ranges that are affected.

\- Casey

**Comment by 4coder-editor** [comment]
I didn't quite do it this way, because updating positions of things usually should be in sync I think.  For instance if a command is visiting ten points in a list, in order to do an edit at each point, and we wait until it's all over to give the user the hook for all edits, and if this list of points is a part of system that expects itself to stay accurate by using that hook... well it's just never going to work.

So instead there's a one-at-a-time callback that gets called for every edit _when_ that edit happens.

**Comment by cmuratori** [comment]
This worked perfectly for me, so I think it's all good now.

\- Casey
