### ISSUE TITLE
Scope for buffer lifetime

### ISSUE THREAD

**Issue by 4coder-editor** [4coder-editor/4coder#70]
Right now a buffer's "scope" is actually tied to the conceptual "file" or "content" of the buffer, and therefore gets cleared and loses values for it's variables making it impossible to stick something on the actual buffer that lasts regardless of changes to the contents of the buffer.

**Comment by cmuratori** [comment]
To give some perspective on this, in case it helps, the things I was doing that care about this tend to be about knowing which buffers are "mine" or have certain properties I want to know about without doing lookups.

So for example, the fbar creates buffers to hold the results of compilations.  When you switch projects, I delete all the file buffers from that project, _but I don't necessarily want to delete the fbar compilation buffers_ because maybe the user still wants to go back and look at some compiles from the previous project.

So in the "close all files for this project" routine, I do a "is this an fbuffer" check and only close the buffer if it _isn't_ one.  I _could_ do this lookup myself in a separate data structure, but it seems better to just do it with a managed variable on the buffer, since that's what it's for.

Since buffers are recycled during compilation, this is where the problem came in: when I would go to compile into one of these fbar buffers, it would clear the marking variable that told me it was one of my special buffers, and so then when I went to ask about it, it would get the wrong answer.  The workaround for this was to just always re-mark the buffers after exec_system_command.  But this seems kind of janky, and probably not what you want.

\- Casey

**Comment by 4coder-editor** [comment]
Yeah, makes perfect sense.

The other solution I considered was just not "ending the file" automatically when doing exec system command.  Then a file would only be "ended" when it's buffer closes, or when a user specifically wants to do the "end file" themselves.  Maybe that's better, I'll figure it out as I'm looking at it.

**Comment by 4coder-editor** [comment]
Didn't do these new scopes.  I went with just giving the user 100% control over the cases that can end a file except that a file is always "ended" when it is literally closed.
