### ISSUE TITLE
What is the idea behind get_user_input's "abort" feature?

### ISSUE THREAD

**Issue by cmuratori** [4coder-editor/4coder#79]
Since the input from get_user_input is returned to you, why do you pass in an "abort" notion?  Wouldn't it be simpler to just have it return to you and you check for the abort?  More broadly, I don't really understand why you pass parameters to this at all.  It seems like it would be more flexible to simply call the function, get something back, and then filter it as necessary into events you want to process and events you don't... that way there aren't hard-coded ways of filtering, which probably don't map very well to what you want?

\- Casey

**Comment by 4coder-editor** [comment]
So this was definitely not a very necessary feature, it was putting extra work on for the programmer on both sides of the API that was usually not helpful. It's only benefit was occasionally saving a context switch-and-switch-back when an event wasn't going to be handled by a coroutine anyway. But that's something that was coming up rarely and no more than once per frame. I simplified the API to get_user_input_raw, and made a helper so that code already written on get_user_input doesn't break. Change in 4.1.6
