### ISSUE TITLE
Autoexit from search mode on editing actions

### ISSUE THREAD

**Issue by paulriddle** [4coder-editor/4coder#97]
Imagine you're doing Ctrl-f to search for something and once found you want to delete the line containing it. You can't just Ctrl-D, you have to hit Esc first. It would be more convenient to autoexit on actions like delete, cut, copy, etc. I think it should be default behavior.

I'm not sure if such minor improvements are in the spirit of 4coder and should be fixed in the main or better left to the user to fix as they please in custom layer.

**Comment by 4coder-editor** [comment]
The problem here is that this would mean distinguishing between commands that should be that anything can be bound to anything. So the system would have to decide upon ignoring some commands, overriding some commands, and exiting for some commands. Then what happens when someone else writes some new custom commands, how does it even decide? As you suggested, you can customize your search to have special exit cases that feel better to you, but I don't think there's a good generic way to do this.
