### ISSUE TITLE
Different font size for different buffers

### ISSUE THREAD

**Issue by paulriddle** [4coder-editor/4coder#98]
I stumbled upon a README file that has pretty long lines. It looks ugly with my font size and line wrapping because almost every line has to be wrapped and it's just a couple of words at the end of each line that doesn't fit. So I like to decrease font size a little bit and it looks perfect. But I don't want font size to change in other buffers.

**Comment by paulriddle** [comment]
I noticed there are already different font sizes in the file I'm editing and in the `*compilation*` buffer.

**Comment by 4coder-editor** [comment]
I added two commands to help with this issue. The first was `set_face_size` which allows you to set the face size by literally just specifying a new size, other methods were a lot more cumbersome. The second command I added was `set_face_size_this_buffer` which first checks to see if the current buffer's face is shared with any others, and if it is, first it makes sure to make a new face for the buffer so that changing it's size won't effect any other buffers. Then it asks for the new size as the other command does. This feature is added in 4.1.4.
